name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false # Set to true after adding a login step for Docker Hub / GHCR
        tags: |
          my-image-name:latest
          my-image-name:${{ github.sha }}
